---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: file-contents-sorter
        files: (.gitignore|requirements.txt)
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        args: [--list-different]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-jsonschema
        files: docker-compose.yml
        args:
          [
            --schemafile,
            https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json,
          ]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: []
        entry: docker compose run --rm -T django mypy
        language: system
        require_serial: true
        types: [python]
